version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends on:
      - frontend-service
  frontend-service:
    image: frontend
    build: FrontEnd/
    ports:
    - target: 5003
      published: 5003
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - SECRET_KEY=${SECRET_KEY}

