version: "3.7"
services:
  frontend-service:
    image: frontend
    container_name: frontend
    build: FrontEnd/
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - SECRET_KEY=${SECRET_KEY}

  central-service:
    image: central-service
    container_name: central
    build: CentralServer

  country-service:
    image: country-service
    container_name: country
    build: CountryGenerator

  account-service:
    image: account-service
    container_name: account
    build: AccountGenerator/

  sort-service:
    image: sort-service
    container_name: sort
    build: SortGenerator/

  cardnumber-service:
    image: cardnumber-service
    container_name: cardnumber
    build: CardNumberGenerator/

  cvc-service:
    image: cvc-service
    container_name: cvc
    build: CVCGenerator/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    depends_on:
      - frontend-service