version: "3.7"
services:
  frontend-service:
    image: jenkins-kube:5000/frontend:${BUILD_NUMBER}
    container_name: frontend
    build: FrontEnd
      context: ./FrontEnd/
      args:
        - USERNAME=${USERNAME}
        - PASSWORD=${PASSWORD}
        - MYSQL_URL=${MYSQL_URL}
        - MYSQL_DB=${MYSQL_DB}
        - MYSQL_DB_TEST=${MYSQL_DB_TEST}
        - SECRET_KEY=${SECRET_KEY}

  central-service:
    image: jenkins-kube:5000/central-service:${BUILD_NUMBER}
    container_name: central
    build: CentralServer

  country-service:
    image: jenkins-kube:5000/country-service:${BUILD_NUMBER}
    deploy:
      replicas: 2
    container_name: country
    build: CountryGenerator

  account-service:
    image: jenkins-kube:5000/account-service:${BUILD_NUMBER}
    deploy:
      replicas: 3
    container_name: account
    build: AccountGenerator/

  sort-service:
    image: jenkins-kube:5000/sort-service:${BUILD_NUMBER}
    deploy:
      replicas: 2
    container_name: sort
    build: SortGenerator/

  cardnumber-service:
    image: jenkins-kube:5000/cardnumber-service:${BUILD_NUMBER}
    deploy:
      replicas: 2
    container_name: cardnumber
    build: CardNumberGenerator/

  cvc-service:
    image: jenkins-kube:5000/cvc-service:${BUILD_NUMBER}
    deploy:
      replicas: 2
    container_name: cvc
    build: CVCGenerator/