version: "3.7"
services:
  frontend-service:
    image: frontend
    container_name: frontend
    build: FrontEnd/
    ports:
    - target: 5003
      published: 5003
    environment:
    - USERNAME=${USERNAME}
    - PASSWORD=${PASSWORD}
    - MYSQL_URL=${MYSQL_URL}
    - MYSQL_DB=${MYSQL_DB}
    - SECRET_KEY=${SECRET_KEY}
  central-service:
    image: central-service
    container_name: central
    build: CentralServer
    ports:
    - target: 5000
      published: 5000
  country-service:
    image: country-service
    container_name: country
    build: CountryGenerator
    ports:
    - target: 5001
      published: 5001
  account-service:
    image: account-service
    container_name: account
    build: AccountGenerator/
    ports:
    - target: 5002
      published: 5002

