apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: frontend-service
  template: 
   metadata:
    labels:
     app: frontend-service
   spec:
    containers:
    - name: frontend-service
      image: jenkins-kube:5000/frontend:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: central-service
  template: 
   metadata:
    labels:
     app: central-service
   spec:
    containers:
    - name: central-service
      image: jenkins-kube:5000/central-service:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cardnumber-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: cardnumber-service
  template: 
   metadata:
    labels:
     app: cardnumber-service
   spec:
    containers:
    - name: cardnumber-service
      image: jenkins-kube:5000/cardnumber-service:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: account-service
  template: 
   metadata:
    labels:
     app: account-service
   spec:
    containers:
    - name: account-service
      image: jenkins-kube:5000/account-service:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cvc-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: cvc-service
  template: 
   metadata:
    labels:
     app: cvc-service
   spec:
    containers:
    - name: cvc-service
      image: jenkins-kube:5000/cvc-service:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: country-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: country-service
  template: 
   metadata:
    labels:
     app: country-service
   spec:
    containers:
    - name: country-service
      image: jenkins-kube:5000/country-service:19

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sort-service
spec:
  replicas: 2
  selector:
   matchLabels:
    app: sort-service
  template: 
   metadata:
    labels:
     app: sort-service
   spec:
    containers:
    - name: cvcgenerator
      image: jenkins-kube:5000/sort-service:19

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-service
  ports: 
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

