- hosts: all
  become: true
  tasks:
  - name: Create Jenkins users
    user:
      name: jenkins
      shell: /bin/bash

- hosts: jenkins
  become: true
  tasks:
  - name: "ssh folder"
    file:
      path: /home/jenkins/.ssh
      state: directory
      mode: "0700"
      owner: jenkins
      group: jenkins
  - name: "Copy private key to jenkins"
    copy:
      src: /home/qa-admin/ansible/jenkins_id_rsa
      dest: /home/jenkins/.ssh/id_rsa
      owner: jenkins
      group: jenkins
      mode: u=rw,g=,o=
  - name: install java
    apt:
      name: openjdk-8-jdk
      state: latest
  - name: jenkins gpg key
    apt_key:
      url: "https://pkg.jenkins.io/debian/jenkins.io.key"
      state: present
  - name: jenkins apt repo
    apt_repository:
      repo: "deb http://pkg.jenkins.io/debian-stable binary/"
      state: present
  - name: jenkins install
    apt:
      name: jenkins
      state: latest
      update_cache: true
  - name: jenkins service
    service:
      name: jenkins
      state: started

- hosts: swarm
  become: true
  tasks:
  - name: "ssh folder"
    file:
      path: /home/jenkins/.ssh
      state: directory
      mode: "0700"
      owner: jenkins
      group: jenkins
  - name: Copy private key to ansible-swarm
    copy:
      src: /home/qa-admin/ansible/jenkins_id_rsa.pub
      dest: /home/jenkins/.ssh/authorized_keys
      owner: jenkins
      mode: u=rw,g=,o=

- hosts: all
  become: true
  tasks:
  - name: update certificates
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      state: latest
      update_cache: true
  - name: docker gpg key
    apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present
  - name: docker apt repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian stretch stable"
      state: present
  - name: docker install
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
      update_cache: true
  - name: docker service
    service:
      name: docker
      state: started
  - name: Add Jenkins user to the Docker group
    user:
      name: jenkins
      groups:
      - docker
      shell: /bin/bash
  - name: "create etc/docker folder"
    file:
      path: /etc/docker
      state: directory
      owner: jenkins
      group: jenkins
    remote_user: jenkins
  - name: "Copy daemon for registry connection"
    copy:
      src: /home/qa-admin/PracticalProject/daemon.json
      dest: /etc/docker/daemon.json
      owner: jenkins
      group: jenkins
    remote_user: jenkins
  - name: docker service
    service:
      name: docker
      state: restarted
    remote_user: jenkins

- hosts: jenkins
  become: true
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      update_cache: yes
      state: present
  - pip:
      name: docker
  - name: registry container
    docker_container:
      name: registry
      image: registry:2
      ports:
      - "5000:5000"
      volumes:
      - registry-volume:/var/lib/registry
    remote_user: jenkins
  - name: Install pip
    apt:
      name: python-pip
      update_cache: yes
      state: present
  - pip:
      name: docker
  - pip:
      name: docker-compose
  - pip:
      name: jsondiff
  - git:
      repo: 'https://github.com/Shaybs/PracticalProject.git'
      dest: /home/jenkins/PracticalProject
      version: development-test
  - name: build images
    docker_compose:
      project_src: /home/jenkins/PracticalProject
      build: yes
    remote_user: jenkins
  - name: push images
    shell: 
      chdir: /home/jenkins/PracticalProject
      cmd: "docker-compose push"
    remote_user: jenkins

- hosts: swarm
  become: true
  tasks:
  - name: Install pip
    apt:
      name: python-pip
      update_cache: yes
      state: present
  - pip:
      name: docker
  - pip:
      name: docker-compose
  - pip:
      name: jsondiff
  - name: initialise swarm
    docker_swarm:
      state: present
    remote_user: jenkins
  - git:
      repo: 'https://github.com/Shaybs/PracticalProject.git'
      dest: /home/jenkins/PracticalProject
      version: development-test
  - name: build images
    docker_compose:
      project_src: /home/jenkins/PracticalProject
      build: yes
    remote_user: jenkins
  - name: push images
    shell: 
      cmd: "cd /home/jenkins/PracticalProject"
      cmd: "docker-compose push"
  - name: Deploy stack from a compose file
    docker_stack:
      state: present
      name: stack
      compose:
        - /home/jenkins/PracticalProject/docker-compose.yaml
  - name: Update stack account service
    docker_swarm_service:
      name: stack_account-service 
      image: ansible-jenkins:5000/account-service:latest
  - name: Update stack cardnumber service
    docker_swarm_service:
      name: stack_cardnumber-service
      image: ansible-jenkins:5000/cardnumber-service:latest
  - name: Update stack central service
    docker_swarm_service:
      name: stack_central-service
      image: ansible-jenkins:5000/central-service:latest
  - name: Update stack country service
    docker_swarm_service:
      name: stack_country-service
      image: ansible-jenkins:5000/country-service:latest
  - name: Update stack cvc service
    docker_swarm_service:
      name: stack_cvc-service
      image: ansible-jenkins:5000/cvc-service:latest
  - name: Update stack frontend service
    docker_swarm_service:
      name: stack_frontend-service
      image: ansible-jenkins:5000/frontend:latest
  - name: Update stack sort service
    docker_swarm_service:
      name: stack_sort-service
      image: ansible-jenkins:5000/sort-service:latest
  - name: Update stack nginx service
    docker_swarm_service:
      name: stack_nginx 
      image: nginx:latest